pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/afparedes/springApi.git'
                dir('hello') {
                      sh "pwd"
                      sh 'mvn clean compile'
                    }

            }
        }
        stage('Test') {
                            steps {
                            dir('hello') {
                                sh 'mvn test'
                                }
                            }
                            post{
                                always{
                                   junit '**/target/surefire-reports/TEST-*.xml'
                                }
                            }
        }
        stage('Publish'){
                            steps {
                            dir('hello') {
                                sh 'mvn package'
                                }
                            }
                             post{
                                  success{
                                      archiveArtifacts 'hello/target/*.jar'
                                   }
                             }
        }
    }
}
