pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/afparedes/springApi.git'
                dir('hello') {
                      sh "pwd"
                      sh "chmod +x mvnw"
                      sh './mvnw clean compile'
                    }

            }
        }
        stage('Test') {
                            steps {
                            dir('hello') {
                            sh "chmod +x mvnw"
                                sh './mvnw test'
                                }
                            }
                            post{
                                always{
                                   junit '**/target/surefire-reports/TEST-*.xml'
                                }
                            }
        }
        stage('Publish'){
                            steps {
                            dir('hello') {
                            sh "chmod +x mvnw"
                                sh './mvnw package'
                                }
                            }
                             post{
                                  success{
                                      archiveArtifacts 'hello/target/*.jar'
                                   }
                             }
        }
    }
}
