pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                git 'https://github.com/afparedes/springApi.git'
                cd 'hello/'
                sh 'mvn clean compile'
            }
        }
        stage('Test') {
                            steps {
                                sh 'mvn test'
                            }
                            post{
                                always{
                                   junit '**/target/surefire-reports/TEST-*.xml'
                                }
                            }
        }
        stage('Publish'){
                            steps {
                                sh 'mvn package'
                            }
                             post{
                                  success{
                                      archiveArtifacts 'target/*.jar'
                                   }
                             }
        }
    }
}
